-- Version: 20260509120000
-- Title: agent_run_store_fk
-- Author: deepseek
-- Created At: 2026-05-09 12:00:00 +08:00
-- Target: mysql8
-- Type: mixed
-- Risk: medium
-- Reversible: no
-- Summary:
-- 1. Add created_at / updated_at columns to agent_run_store.
-- 2. Add index on agent_run_store.user_id.
-- 3. Clean orphan rows in agent_run_store that have no matching chat_sessions row.
-- 4. Add foreign key from agent_run_store.session_id to chat_sessions.agno_session_id with ON DELETE CASCADE.
--
-- Pre-Checks:
-- 1. Confirm a full database backup has completed.
-- 2. Confirm the chat_sessions table exists and has the agno_session_id column.
-- 3. Run: SELECT COUNT(*) FROM agent_run_store WHERE session_id NOT IN (SELECT agno_session_id FROM chat_sessions);
--    If count > 0, review orphan rows before proceeding (they will be deleted).
--
-- Execution Notes:
-- 1. Execute during a low-traffic window.
-- 2. Do not edit this file after it is committed.
-- 3. The DELETE step may lock agent_run_store rows briefly.
--
-- Post-Checks:
-- 1. SHOW CREATE TABLE agent_run_store;
-- 2. SELECT COUNT(*) FROM agent_run_store WHERE session_id NOT IN (SELECT agno_session_id FROM chat_sessions);
--    Should return 0.
-- 3. Verify chat send / receive flows still work.

ALTER TABLE agent_run_store
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX ix_agent_run_store_user_id ON agent_run_store (user_id);

-- Clean orphan rows before adding the foreign key
DELETE FROM agent_run_store
WHERE session_id NOT IN (SELECT agno_session_id FROM chat_sessions);

ALTER TABLE agent_run_store
  ADD CONSTRAINT fk_agent_run_store_session_id__chat_sessions
  FOREIGN KEY (session_id) REFERENCES chat_sessions (agno_session_id) ON DELETE CASCADE;
