-- Version: 20260508223247
-- Title: initial_schema
-- Author: Codex
-- Created At: 2026-05-08 22:32:47 +08:00
-- Target: mysql8
-- Type: schema
-- Risk: medium
-- Reversible: no
-- Summary:
-- 1. Create the initial GoodGua application schema from the current SQLAlchemy models.
-- 2. Create the Agno runtime agent_sessions table used by the chat agent session store.
-- 3. Create required indexes, unique constraints, and foreign keys with explicit names.
--
-- Pre-Checks:
-- 1. Confirm this migration is being executed against an empty MySQL database.
-- 2. Confirm a full database backup or restore point is available before production execution.
-- 3. Confirm the application is not running against the target database during initial schema creation.
--
-- Execution Notes:
-- 1. Execute this file manually in MySQL before starting production services.
-- 2. Do not edit this file after it is committed.
-- 3. All tables use InnoDB, utf8mb4, and utf8mb4_unicode_ci.
--
-- Post-Checks:
-- 1. SHOW TABLES;
-- 2. SHOW CREATE TABLE users;
-- 3. SHOW CREATE TABLE agent_sessions;
-- 4. Start the application and verify health check, login, workspace, billing config, and chat paths.

CREATE TABLE agent_sessions (
    session_id VARCHAR(128) NOT NULL,
    session_type VARCHAR(20) NOT NULL,
    agent_id VARCHAR(128),
    team_id VARCHAR(128),
    workflow_id VARCHAR(128),
    user_id VARCHAR(128),
    session_data JSON,
    agent_data JSON,
    team_data JSON,
    workflow_data JSON,
    metadata JSON,
    runs JSON,
    summary JSON,
    created_at BIGINT NOT NULL,
    updated_at BIGINT,
    PRIMARY KEY (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_agent_sessions_created_at ON agent_sessions (created_at);
CREATE INDEX idx_agent_sessions_session_type ON agent_sessions (session_type);

CREATE TABLE agent_run_store (
    session_id VARCHAR(100) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    runs JSON NOT NULL,
    PRIMARY KEY (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ai_models (
    id VARCHAR(36) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    provider_model_id VARCHAR(100) NOT NULL,
    description TEXT,
    logic_score INTEGER NOT NULL,
    prose_score INTEGER NOT NULL,
    knowledge_score INTEGER NOT NULL,
    max_context_tokens INTEGER NOT NULL,
    max_output_tokens INTEGER NOT NULL,
    temperature NUMERIC(3, 2) NOT NULL,
    input_cost_per_million NUMERIC(10, 4) NOT NULL,
    cache_hit_input_cost_per_million NUMERIC(10, 4) NOT NULL,
    output_cost_per_million NUMERIC(10, 4) NOT NULL,
    profit_multiplier NUMERIC(5, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    sort_order INTEGER,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_ai_models_provider_model_id UNIQUE (provider_model_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_ai_models_sort_order ON ai_models (sort_order);
CREATE INDEX ix_ai_models_status ON ai_models (status);

CREATE TABLE credit_packs (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price_amount NUMERIC(10, 2) NOT NULL,
    price_currency VARCHAR(10) NOT NULL,
    points INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    sort_order INTEGER,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_credit_packs_status ON credit_packs (status);

CREATE TABLE global_configs (
    id VARCHAR(36) NOT NULL,
    config_group VARCHAR(100) NOT NULL,
    config_key VARCHAR(100) NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    string_value TEXT,
    integer_value INTEGER,
    decimal_value NUMERIC(18, 6),
    boolean_value BOOL,
    json_value JSON,
    description TEXT,
    is_required BOOL NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_global_configs_config_group_config_key UNIQUE (config_group, config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_global_configs_config_group ON global_configs (config_group);
CREATE INDEX ix_global_configs_value_type ON global_configs (value_type);

CREATE TABLE login_audits (
    id VARCHAR(36) NOT NULL,
    email VARCHAR(200) NOT NULL,
    user_id VARCHAR(36),
    `role` VARCHAR(20),
    success BOOL NOT NULL,
    reason VARCHAR(100) NOT NULL,
    ip_address VARCHAR(100),
    user_agent TEXT,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_login_audits_created_at ON login_audits (created_at);
CREATE INDEX ix_login_audits_email ON login_audits (email);
CREATE INDEX ix_login_audits_ip_address ON login_audits (ip_address);
CREATE INDEX ix_login_audits_role ON login_audits (`role`);
CREATE INDEX ix_login_audits_success ON login_audits (success);
CREATE INDEX ix_login_audits_user_id ON login_audits (user_id);

CREATE TABLE plans (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price_amount NUMERIC(10, 2) NOT NULL,
    price_currency VARCHAR(10) NOT NULL,
    billing_cycle_months INTEGER NOT NULL,
    daily_vip_points INTEGER NOT NULL,
    bundled_credit_pack_points INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    sort_order INTEGER,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_plans_status ON plans (status);

CREATE TABLE users (
    id VARCHAR(36) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    `role` VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_login_at DATETIME,
    password_changed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_users_role ON users (`role`);
CREATE INDEX ix_users_status ON users (status);

CREATE TABLE billing_orders (
    id VARCHAR(36) NOT NULL,
    order_no VARCHAR(50) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    product_name_snapshot VARCHAR(200) NOT NULL,
    daily_vip_points_snapshot INTEGER,
    bundled_credit_pack_points_snapshot INTEGER,
    credit_pack_points_snapshot INTEGER,
    duration_days_snapshot INTEGER,
    pay_channel VARCHAR(30),
    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_at DATETIME,
    closed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_billing_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_billing_orders_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_billing_orders_status ON billing_orders (status);
CREATE INDEX ix_billing_orders_user_id ON billing_orders (user_id);

CREATE TABLE point_accounts (
    id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    vip_daily_points_balance NUMERIC(12, 2) NOT NULL,
    credit_pack_points_balance NUMERIC(12, 2) NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_point_accounts_user_id UNIQUE (user_id),
    CONSTRAINT fk_point_accounts_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE point_transactions (
    id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    bucket_type VARCHAR(20) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id VARCHAR(36),
    points_delta NUMERIC(12, 2) NOT NULL,
    work_id VARCHAR(36),
    model_id VARCHAR(36),
    model_name_snapshot VARCHAR(100),
    provider_model_id_snapshot VARCHAR(100),
    prompt_cache_hit_tokens INTEGER,
    prompt_cache_miss_tokens INTEGER,
    completion_tokens INTEGER,
    input_cost_per_million_snapshot NUMERIC(10, 4),
    cache_hit_input_cost_per_million_snapshot NUMERIC(10, 4),
    output_cost_per_million_snapshot NUMERIC(10, 4),
    profit_multiplier_snapshot NUMERIC(5, 2),
    points_per_cny_snapshot NUMERIC(10, 4),
    balance_after NUMERIC(12, 2),
    description VARCHAR(500),
    expire_at DATETIME,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_point_transactions_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_point_transactions_bucket_type ON point_transactions (bucket_type);
CREATE INDEX ix_point_transactions_created_at ON point_transactions (created_at);
CREATE INDEX ix_point_transactions_expire_at ON point_transactions (expire_at);
CREATE INDEX ix_point_transactions_user_id ON point_transactions (user_id);

CREATE TABLE works (
    id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    title VARCHAR(200) NOT NULL,
    short_intro TEXT NOT NULL,
    synopsis TEXT NOT NULL,
    genre_tags JSON NOT NULL,
    background_rules TEXT NOT NULL,
    focus_requirements TEXT,
    forbidden_requirements TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_works_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_works_user_id ON works (user_id);

CREATE TABLE characters (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_characters_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_characters_name ON characters (name);
CREATE INDEX ix_characters_work_id ON characters (work_id);

CREATE TABLE chat_sessions (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    agno_session_id VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    last_message_preview TEXT,
    last_active_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_chat_sessions_agno_session_id UNIQUE (agno_session_id),
    CONSTRAINT fk_chat_sessions_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_sessions_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_chat_sessions_last_active_at ON chat_sessions (last_active_at);
CREATE INDEX ix_chat_sessions_user_id ON chat_sessions (user_id);
CREATE INDEX ix_chat_sessions_work_id ON chat_sessions (work_id);

CREATE TABLE daily_word_progress (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    date DATE NOT NULL,
    words_added INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_daily_word_progress_work_id_date UNIQUE (work_id, date),
    CONSTRAINT fk_daily_word_progress_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_daily_word_progress_date ON daily_word_progress (date);
CREATE INDEX ix_daily_word_progress_work_id ON daily_word_progress (work_id);

CREATE TABLE inspiration_notes (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_inspiration_notes_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_inspiration_notes_category ON inspiration_notes (category);
CREATE INDEX ix_inspiration_notes_work_id ON inspiration_notes (work_id);

CREATE TABLE payment_records (
    id VARCHAR(36) NOT NULL,
    order_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    out_trade_no VARCHAR(50) NOT NULL,
    trade_no VARCHAR(100),
    channel_status VARCHAR(30),
    qr_code TEXT,
    notify_verified BOOL,
    last_notify_at DATETIME,
    raw_notify_payload JSON,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_payment_records_out_trade_no UNIQUE (out_trade_no),
    CONSTRAINT fk_payment_records_order_id__billing_orders FOREIGN KEY (order_id) REFERENCES billing_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_records_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_payment_records_channel ON payment_records (channel);
CREATE INDEX ix_payment_records_channel_status ON payment_records (channel_status);
CREATE INDEX ix_payment_records_order_id ON payment_records (order_id);
CREATE INDEX ix_payment_records_trade_no ON payment_records (trade_no);
CREATE INDEX ix_payment_records_user_id ON payment_records (user_id);

CREATE TABLE settings (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_settings_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_settings_name ON settings (name);
CREATE INDEX ix_settings_type ON settings (type);
CREATE INDEX ix_settings_work_id ON settings (work_id);

CREATE TABLE user_subscriptions (
    id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    plan_id VARCHAR(36) NOT NULL,
    order_id VARCHAR(36),
    status VARCHAR(20) NOT NULL,
    start_at DATETIME NOT NULL,
    end_at DATETIME NOT NULL,
    next_renew_at DATETIME,
    daily_vip_points_snapshot INTEGER NOT NULL,
    duration_days_snapshot INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_subscriptions_user_id__users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_subscriptions_plan_id__plans FOREIGN KEY (plan_id) REFERENCES plans (id),
    CONSTRAINT fk_user_subscriptions_order_id__billing_orders FOREIGN KEY (order_id) REFERENCES billing_orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_user_subscriptions_plan_id ON user_subscriptions (plan_id);
CREATE INDEX ix_user_subscriptions_status ON user_subscriptions (status);
CREATE INDEX ix_user_subscriptions_user_id ON user_subscriptions (user_id);

CREATE TABLE volumes (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_volumes_work_id_order_index UNIQUE (work_id, order_index),
    CONSTRAINT fk_volumes_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_volumes_order_index ON volumes (order_index);
CREATE INDEX ix_volumes_work_id ON volumes (work_id);

CREATE TABLE writing_goals (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    target_words INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_writing_goals_work_id UNIQUE (work_id),
    CONSTRAINT fk_writing_goals_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE chapters (
    id VARCHAR(36) NOT NULL,
    work_id VARCHAR(36) NOT NULL,
    volume_id VARCHAR(36),
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_chapters_volume_id_order_index UNIQUE (volume_id, order_index),
    CONSTRAINT fk_chapters_work_id__works FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE,
    CONSTRAINT fk_chapters_volume_id__volumes FOREIGN KEY (volume_id) REFERENCES volumes (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_chapters_order_index ON chapters (order_index);
CREATE INDEX ix_chapters_volume_id ON chapters (volume_id);
CREATE INDEX ix_chapters_work_id ON chapters (work_id);

CREATE TABLE payment_notify_logs (
    id VARCHAR(36) NOT NULL,
    payment_record_id VARCHAR(36),
    channel VARCHAR(30) NOT NULL,
    out_trade_no VARCHAR(50),
    trade_no VARCHAR(100),
    notify_body JSON NOT NULL,
    verify_result VARCHAR(20) NOT NULL,
    process_result VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_payment_notify_logs_payment_record_id__payment_records FOREIGN KEY (payment_record_id) REFERENCES payment_records (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX ix_payment_notify_logs_created_at ON payment_notify_logs (created_at);
CREATE INDEX ix_payment_notify_logs_out_trade_no ON payment_notify_logs (out_trade_no);
CREATE INDEX ix_payment_notify_logs_trade_no ON payment_notify_logs (trade_no);
